CREATE TABLE IF NOT EXISTS incomeinfo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Money DECIMAL(10, 2) NOT NULL,
    Category VARCHAR(255) NOT NULL,
    Yapping TEXT,
    Income_Day DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expenseinfo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Money DECIMAL(10, 2) NOT NULL,
    Category VARCHAR(255) NOT NULL,
    Yapping TEXT,
    Expense_Day DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
